steps:
  - name: node
    entrypoint: npm
    args: ['run', 'heroku-postbuild']

    # Install dependencies
  - name: python
    entrypoint: pip
    args: ["install", "-r", "requirements.txt"]
  # Docker Build

  - name: node
    entrypoint: npm
    args: ['start']

  - name: 'gcr.io/cloud-builders/gcloud'
    entrypoint: 'bash'
    args: ['-c', 'gcloud config set app/cloud_build_timeout 1800 && gcloud app deploy my-service/my-config.yaml']